name: MCTranslationLib
version: '${project.version}'
main: fr.keykatyu.mctranslation.Main
api-version: '1.20'
authors: [KeyKatyu]
description: 'A Java Spigot library for translating Minecraft elements using their translation key.'